riftChance: 0.00
riftChanceIncrease: 0.25
minimumKillsStreak: 20
killStreakTimer: 8000
minY: 50
worlds:
  - world

killStreakStartedAnnouncement: You can feel the oppressive anger of Herobrine building...
killStreakEndedAnnouncement: Herobrine's presence fades.
playerDeathAnnouncement: Herobrine chuckles, his rage subsides slightly after witnessing PLAYER's demise.

    
waves:
  normalwarning:
    killStreakThreshold: 18
    announcement: You hear a crackling in the air that sets your hairs on end...
    isSummon: false
  normal:
    killStreakThreshold: 20
    announcement: A rift has opened! You hear maniacal laughter from the other side..
    isSummon: true
    possibleMobs:
      - Spider
      - CaveSpider
    minMobs: 5
    maxMobs: 10
    cooldown: 5
  spiders:
    killStreakThreshold: 25
    announcement: The skittering of hundreds of legs...
    isSummon: true
    possibleMobs:
      - Spider
      - CaveSpider
    minMobs: 5
    maxMobs: 12
    cooldown: 5
  creeperwarning:
    killStreakThreshold: 28
    announcement: Herobrine's rage grows as you slay his minions... beware his wrath lest they explode!
    isSummon: false
  creepers:
    killStreakThreshold: 30
    announcement: Tssssss...
    isSummon: true
    possibleMobs:
      - Creeper
    minMobs: 2
    maxMobs: 10
    cooldown: 15
  netherwarning:
    killStreakThreshold: 38
    announcement: You dare fight on against his minions?! You will suffer!
    isSummon: false
  nether:
    killStreakThreshold: 40
    announcement: Herobrine summons hideous monsters from the depths!
    isSummon: true
    possibleMobs:
      - WitherSkeleton
      - PigZombie
      - Blaze
    minMobs: 2
    maxMobs: 10
    cooldown: 10
  cronewarning:
    killStreakThreshold: 55
    announcement: The air grows dense. What will Herobrine send next to plague you?
    isSummon: false
  crones:
    killStreakThreshold: 60
    announcement: The sound of crones cackling approaches...
    isSummon: true
    possibleMobs:
      - Witch
    minMobs: 1
    maxMobs: 6
    cooldown: 10
  bosswarning:
    killStreakThreshold: 95
    announcement: YOUR END IS NEAR.
    isSummon: false
  bosses:
    killStreakThreshold: 100
    announcement: DOOM IS UPON YOU!
    isSummon: true
    possibleMobs:
      - Wither
    minMobs: 1
    maxMobs: 1
    cooldown: 600